name: Setup
description: Setup Node.js, cache npm, and install dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: lts/*

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci
